const discographyList = [
    ["The Day She Cried", 2024, "Trio w/ Joe Fonda & Barry Altschul", "Modern Improvisation", "https://stevecohn.bandcamp.com/album/the-day-she-cried"],
    ["Hyperborean", 2024, "Quartet w/ James Witte-Cook, Ratzo Harris & Francisco Mela", "Modern Improvisation", "https://stevecohn.bandcamp.com/album/hyperborean"],
    ["Ichigo Ichie", 2024, "Duo w/ Carl Baugher", "Tube Room Records", "https://carlbaugher.bandcamp.com/album/ichigo-ichie"],
    ["Arts and Crafts", 1984, "Trio w/ Jay Elfenbein & Chuck Fertal", "White Cow", "https://stevecohn.bandcamp.com/album/arts-crafts"],
    ["Shapes, Sounds, Theories", 1984, "Trio w/ Reggie Workman & Chuck Fertal", "Cadence"],
    ["Clay Bird Square", 1984, "Trio w/ Reggie Workman & Chuck Fertal", "Modern Improvisation", "https://stevecohn.bandcamp.com/album/clay-bird-square"],
    ["The Beggar and the Robot In Diamonds", 1993, "Quartet w/ Fred Hopkins, Jason Kao Hwang & Tom Varner; sextet w/ Frank Lowe, William Parker, Bob Stewart, Karl Berger & Zen Matsuura", "ITM Pacific", "https://stevecohn.bandcamp.com/album/the-beggar-and-the-robot-in-diamonds"],
    ["Ittekimasu (Live at Greenwich Village Jazz Festival)", 1987, "Trio w/ Fred Hopkins & Thurman Barker", "White Cow & ITM Pacific", "https://stevecohn.bandcamp.com/album/ittekimasu"],
    ["Sufi Dancers", 1982, "Quintet w/ Warren Gale, David Schrader, John Donnelly & Larry Hancock", "White Cow", "https://stevecohn.bandcamp.com/album/sufi-dancers-bonus-tracks-edition"],
    ["Bridge Over The X-Stream (Live at the Knitting Factory)", 1999, "Quartet w/ Reggie Workman, Jason Kao Hwang & Tom Varner", "Leo", "https://stevecohn.bandcamp.com/album/bridge-over-the-x-stream"],
    ["Live In New York", 1997, "Trio w/ William Parker & Denis Charles", "Tube Room", "https://carlbaugher.bandcamp.com/album/live-in-new-york"],
    ["Anspruchsvoll", 2012, "Solo piano", "Unseen Rain", "https://www.youtube.com/playlist?list=OLAK5uy_lFcIr4M2Hcs-NLdLwFArkpmNu4VsNRc-E"],
    ["Manhattan 2 Moonshine", 2012, "Solo piano", "Mega International"],
    ["Faces", 2013, "Duo w/ Perry Robinson", "Tube Room", "https://carlbaugher.bandcamp.com/album/faces"],
    ["Dream Time", 2018, "New York Free Quartet w/ Michael Moss, Larry Roland & Chuck Fertal", "4th Stream", "https://michaelmoss.bandcamp.com/album/dream-time"],
    ["In Between Gigs... Can You Dig?", 2017, "New York Free Quartet w/ Michael Moss, Larry Roland & Chuck Fertal", "4th Stream", "https://michaelmoss.bandcamp.com/album/in-between-gigs-can-you-dig"],
    ["Free Play", 2015, "New York Free Quartet w/ Michael Moss, Larry Roland & Chuck Fertal", "4th Stream", "https://michaelmoss.bandcamp.com/album/free-play"],
    ["Wind Shape", 2020, "Quartet w/ James Cook, Mike Harmon & Chuck Fertal", "Tube Room", "https://carlbaugher.bandcamp.com/album/wind-shape"],
    ["The Novel", 2010, "Quartet w/ Guillermo Gregorio, Masahiko Kono & Bruce Ditmas", "Modern Improvisation", "https://stevecohn.bandcamp.com/album/the-novel"],
    ["Round the World", 2013, "Solo piano", "Unseen Rain"],
    ["We", 1991, "Trio w/ William Parker & Tom Tedesco", "Modern Improvisation", "https://stevecohn.bandcamp.com/album/we"],
    ["Iro Iro (Live at Knitting Factory)", 1991, "Quartet w/ Masahiko Kono, Tomas Ulrich & Kevin Norton", "Red Toucan", "https://stevecohn.bandcamp.com/album/iro-iro"],
    ["Wire", 2007, "Quintet w/ Adam Lane, Ray Sage, Blaise Siwula & Motoko Shimizu", "Konnex"],
    ["Voyager", 2018, "Quartet w/ Daniel Carter, Larry Roland & Marvin Bugalu Smith", "Tube Room", "https://carlbaugher.bandcamp.com/album/voyager"],
    ["Quarter to Three", 2017, "Trio w/ Annabelle Plum & Marek Kimel Matvija", "Poli5", "https://quartertothree.bandcamp.com/album/quarter-to-three"],
    ["Converzations with Jules", 2021, "Trio w/ Bob Stewart & Barry Altschul", "Modern Improvisation", "https://stevecohn.bandcamp.com/album/converzations-with-jules"],
    ["Futurity", 2018, "Trio w/ John Marglin & Carl Baugher", "Tube Room", "https://carlbaugher.bandcamp.com/album/futurity"],
    ["Helix", 2017, "Michael Moss Accidental Orchestra", "4th Stream", "https://michaelmoss.bandcamp.com/album/helix"],
    ["Me Being Me", 2018, "Solo piano", "Mega International"],
    ["Seven Steps To Infinity", 2006, "w/ Anthony Mirabile & Doc Holiday", "Mega International"],
    ["Albany Park", 2018, "Duo w/ Jimmy Bennington", "Slam Records"],
    ["Kings In The Mountain", 2022, "Trio w/ Thomas Milovac & Ben Shorstein", "Cosmosonic Collective"],
    ["Echo", 2020, "Duo w/ Carl Baugher", "Tube Room", "https://carlbaugher.bandcamp.com/album/echo"],
    ["Cowboy Film School", 2008, "Quartet w/ Tony Decicco, Bruce Ditmas & Chris Kelsey", "Unseen Rain"],
    ["Spokenash", 2019, "Quintet w/ Anthony Mirabile, Dale Herr, David Roe & Craig Krampt", "Mega International"],
    ["The Blair Recordings", 2002, "w/ Blair Hardman & Johnny De Robertis", "Leo"],
    ["Ancient & Modern", 2019, "Trio w/ George Haslam & Steve Kershaw", "Slam Records"],
    ["Music", 2019, "Duo w/ David Pate", "Self-published", "https://davidpate.bandcamp.com/album/music"],
    ["Falling Outside The Normal Moral Constaints", 2022, "Trio w/ Thomas Milovac & Ben Shorstein", "Cosmosonic Collective", "https://cosmosoniccollective.bandcamp.com/album/falling-outside-the-normal-moral-constraints"],
    ["No Lunch in Hackensack", 2013, "Duo w/ Jimmy Bennington", "That Swan"],
    ["New Jersey Freebie", 2019, "Trio w/ Ed Schuller & Jimmy Bennington", "Slam Records"],
    ["Moody O Kyo", 2018, "Trio w/ Kyo Inaba & Santi Debriano", "Kojak"],
    ["At Home", 2021, "Solo piano", "Tube Room", "https://carlbaugher.bandcamp.com/album/at-home"],
    ["Iro Iro Volume 2 (Live at Knitting Factory)", 1998, "Quartet w/ Kevin Norton, Masahiko Kono & Tomas Ulrich", "Modern Improvisation", "https://stevecohn.bandcamp.com/album/iro-iro-band-volume-2"],
    ["Arts and Crafts: The Alternate Takes", 1984, "Trio w/ Jay Elfenbein & Chuck Fertal", "White Cow", "https://stevecohn.bandcamp.com/album/arts-crafts-the-alternate-takes"]
];